import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const vaultPluginDir = path.join(
	'vault',
	'.obsidian',
	'plugins',
	'snippet-templater',
);

const copyToVaultPlugin = {
	name: 'copy-to-vault',
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length === 0) {
				try {
					if (!fs.existsSync(vaultPluginDir)) {
						fs.mkdirSync(vaultPluginDir, { recursive: true });
					}
					if (fs.existsSync('main.js')) {
						fs.copyFileSync('main.js', path.join(vaultPluginDir, 'main.js'));
					}
					if (fs.existsSync('manifest.json')) {
						fs.copyFileSync(
							'manifest.json',
							path.join(vaultPluginDir, 'manifest.json'),
						);
					}
					if (fs.existsSync('styles.css')) {
						fs.copyFileSync('styles.css', path.join(vaultPluginDir, 'styles.css'));
					}
					console.log(`[build] Copied build output to ${vaultPluginDir}`);
				} catch (err) {
					console.error('[build] Failed to copy build output to vault:', err);
				}
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [copyToVaultPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
